### PR TITLE
Fix RT 55357 by adding some accessor functions

### PR DESCRIPTION
**Pull request by ozcoder**
Also added date utility subroutine sf_date.

### CODE REVIEW

**Comment by genio** [comment]
The travis.yml is very badly done for Perl projects.

Here's an example of a more proper one: https://github.com/genio/www-salesforce-nb/blob/master/.travis.yml

**Comment by ozcoder** [comment]
Added Perl testing with versions 5.8, 5.10, 5.12, 5.14, 5.16, 5.18, 5.20 and 5.22. 
Also created tests in different time zones for sf_date().

**Comment by genio** [comment]
@ozcoder Thanks for the PR!  Please keep the ideas/updates coming!

I'll go through some testing of it this weekend, but at a glance your test additions and TravisCI looks good. @redhotpenguin will have the final say, but I'll do my best to audit and let you know if there are any further requirements for a successful merge to look into.

Tentative :+1: from me for now.

**Comment by redhotpenguin** [comment]
Looks good!

**Pull request merged**
