### PR TITLE
Documentation Updates

### PR DESCRIPTION
**Pull request by genio**
I made some POD updates and alphabetized.  I fixed a few Makefile things, added some POD and POD Coverage tests. More work needs doing, but this is a start.

No actual code changes were made.

### CODE REVIEW

**Comment by redhotpenguin** [comment]
Hey I'm getting this error - did you mean to include t/pod.t and t/pod-coverage.t?

**Comment by redhotpenguin** [comment]
Warning: the following files are missing in your kit:
	t/pod-coverage.t
	t/pod.t

**Comment by genio** [comment]
oops.  I forgot a "git add" in there.  Apologies.  I'll fix that in just a
second.

**Comment by redhotpenguin** [comment]
I added some last night, can you take a look at the release I pushed?

**Comment by genio** [comment]
Yours was more or less exactly what I had, minus the check for the
ENV{TEST_POD}  submitted another pull request to make that change.  Sorry
about the mixup.

**Pull request merged**
